### ISSUE TITLE
Font DejaVuSans/10 could not be loaded!

### ISSUE THREAD

**Issue by zvezdochiot** [Tomas-M/xlunch#103]
$ xlunch
Font DejaVuSans/10 could not be loaded! Please specify one with -f parameter
$ xlunch -f DejaVuSans/10
Font DejaVuSans/10 could not be loaded! Please specify one with -f parameter
$ xlunch -f Tahoma/10
Font Tahoma/10 could not be loaded! Please specify one with -f parameter

$ file /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf 
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf: TrueType font data

**Comment by PMunch** [comment]
`xlunch` only reads fonts from these folders:

- `~/.local/share/fonts`
- `~/.fonts`
- `/usr/local/share/fonts`
- `/usr/share/fonts/truetype`
- `/usr/share/fonts/truetype/dejavu`
- `/usr/share/fonts/TTF`

The imlib search is not recursive, so any sub-folders will not be searched (as can be seen by the inclusion of both `/usr/share/fonts/truetype` and `/usr/share/fonts/truetype/dejavu`. One option would be to also add `ttf-dejavu` but I think the better option would be to use [this](http://pubs.opengroup.org/onlinepubs/9699919799//functions/nftw.html) and add all sub-folders as fonts-path in imlib.

**Comment by zvezdochiot** [comment]
Can i use simlink?:

 /usr/share/fonts/truetype/ttf-dejavu/ -> /usr/share/fonts/truetype/dejavu

**Comment by PMunch** [comment]
Not sure really, but it might. Try it!

**Comment by zvezdochiot** [comment]
Yes! Simlink work.

**Comment by PMunch** [comment]
Good to hear that symlinks worked. At least you have a workaround until we can add all folders recursively.

**Comment by lzap** [comment]
For the record, this worked previously. I upgraded from some ancient version today and this is no longer an option:

     xlunch -f /usr/share/fonts/google-roboto/RobotoCondensed-Regular.ttf/10

**Comment by PMunch** [comment]
Are you sure you have the path right? Running `xlunch -f <path to font>/<size of font>` works fine for me on the latest version.

Note that if you come from a really old version the `-f` option has been split into `-f` for the font to use for entry names and `-F` for the font to use for the prompt.

**Comment by lzap** [comment]
Yes, pretty sure:

    file /usr/share/fonts/google-roboto/RobotoCondensed-Regular.ttf
    /usr/share/fonts/google-roboto/RobotoCondensed-Regular.ttf: TrueType Font data, 13 tables, 1st "GDEF", 14 names, Microsoft, language 0x409, Copyright 2011 Google Inc. All Rights Reserved.Roboto CondensedRegularGoogle:Roboto Condensed R

**Comment by PMunch** [comment]
That's very strange, works fine for me with xlunch 4.1.1. Haven't tried that specific font though, but I doubt that's the problem. Does xlunch complain about anything if you run it from a terminal with that parameter?

**Comment by lzap** [comment]
Damn, apologies solved it. It was `-r` option which now requires number:

```
[lzap@box xlunch]$ /home/lzap/work/xlunch/xlunch -r -f /usr/share/fonts/google-roboto/RobotoCondensed-Regular.ttf/10
Font  could not be loaded! Please specify one with -f parameter
[lzap@box xlunch]$ /home/lzap/work/xlunch/xlunch -f /usr/share/fonts/google-roboto/RobotoCondensed-Regular.ttf/10
# now it works
```

**Comment by PMunch** [comment]
Yeah, a lot of the parameters were renamed or have changed how they work since the early versions. Still a bit strange that you get that error though..
