### ISSUE TITLE
Can't seem to get desktop mode working in latest version (4.4.2)

### ISSUE THREAD

**Issue by cablespaghetti** [Tomas-M/xlunch#108]
I've just discovered xlunch and installed it on top of i3 in Arch Linux, using your tip of adding it to the bottom of the i3 config file. However with 4.4.2 whether I do this or try and run it directly after i3 has loaded, it is never visible at all in desktop mode (I also tried openbox) although it does work when run with no parameters.

I built 3.2.13 just to try and older version and that works just fine, so I guess there is a regression here. Let me know if I can provide any more useful information.

**Comment by Tomas-M** [comment]
Can you please try few more versions to find out which one still works and which one stops working? That would help to track down the issue. Thank you.

**Comment by Tomas-M** [comment]
Try to run it with --xposition 0 --yposition 0

**Comment by Tomas-M** [comment]
Should be fixed in v4.4.4
https://github.com/Tomas-M/xlunch/releases/tag/v4.4.4

**Comment by PMunch** [comment]
Hmm, I'm also running i3 on Arch, but with 4.1.2 and `--desktop` worked fine for me.

**Comment by cablespaghetti** [comment]
Thanks for the super quick response!

**Comment by Tomas-M** [comment]
@PMunch
It is because it was broken by my changes in 4.2.x or 4.3.x or something, where I implemented negative positioning, like --yposition -200... to put xlunch window 200px above the bottom of screen. 

Anyway it is now fixed.
