### ISSUE TITLE
Ability to set window title?

### ISSUE THREAD

**Issue by Botspot** [Tomas-M/xlunch#118]
I'm using `xlunch` in windowed mode. (Fullscreen is not to my liking)

The xlunch window is titled "xlunch: Graphical app launcher". Is there any way to change it? It appears to be hard-coded on [line 2451](https://github.com/Tomas-M/xlunch/blob/2da52278c400ccce53c19c80b6323cf76d85676b/xlunch.c#L2451).  
Please consider adding such an option.

**Comment by PMunch** [comment]
Ah, yes this is hard-coded without any way of changing it. To be honest I don't think I have ever run it in windowed mode, so I simply never noticed that. But adding an option for this should be simply, do you have any suggestions for a switch name?

**Comment by Botspot** [comment]
@PMunch If you need a suggestion for the command-line switch, why not `--title`?

That's how [yad](http://smokey01.com/yad/) does it at least. A short-version command flag, I would just skip it TBH.

**Comment by Botspot** [comment]
In case you're curious, I'm planning on using xlunch for my [Raspberry Pi app store](https://github.com/Botspot/pi-apps).  
![2020-11-26-082755_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/100362681-5b300780-2fc1-11eb-99cb-278cb9805a37.png)

**Comment by PMunch** [comment]
This is fixed in https://github.com/Tomas-M/xlunch/commit/71517d5824e4bf95244f0a30fdbb27f466394d68 (I messed up the commit a bit..).

That project looks really cool! Just out of curiosity, how did you end up using xlunch for the UI?

**Comment by Botspot** [comment]
> That project looks really cool! Just out of curiosity, how did you end up using xlunch for the UI?

I've been using the YAD dialog system. While it works fine, there's no search tool, and every new app that's added to the list makes YAD take a little longer to launch. If we keep up with the growth rate, I'll be forced to limit the number of apps displayed in the yad dialog at once to keep a reasonable launch time.  
Here's the current yad window:  
![main window](https://user-images.githubusercontent.com/54716352/100457261-559cf500-3087-11eb-9181-2549ec4aa897.png)
And then also, xlunch looks so much cooler than yad for doing this. The transparency, the hovering rectangle, the mouse pointer changing states to the "over link" state, etc. Keep up the great work!
