### ISSUE TITLE
Ability to set window icon?

### ISSUE THREAD

**Issue by Botspot** [Tomas-M/xlunch#119]
I'm using `xlunch` in windowed mode. (Fullscreen is not to my liking)  
The xlunch window is an ugly generic program icon on the taskbar and on the titlebar, and there appears to be no way to change it.

Consider adding such an option.

**Comment by PMunch** [comment]
Added this as an option (with `--icon`), my WM doesn't have icons on windows, so not 100% sure if it works, but according to xprop it appears to work.

**Comment by Botspot** [comment]
Oh, looks like it's not open source... So there's no compiling it. Interesting.

**Comment by Botspot** [comment]
Posted something above in the wrong github issue - sorry!
