### ISSUE TITLE
Suggestion: Subsequent hitting of TAB moves to next item

### ISSUE THREAD

**Issue by elpraga** [Tomas-M/xlunch#12]
I just notices that I quite often write a partial command, then hit TAB (because it is the most convenient key) just to find out that I have to move my hands completely to reach the right key to select second item in the list.

Do you think it would be a good idea to move to next item after hitting TAB again?  

Would it be doable and simple enough to implement or is there another reason for current behavior?

**Comment by Tomas-M** [comment]
Good idea, check latest releaase v2.4.0

**Comment by elpraga** [comment]
Great!
Works like a charm!

**Comment by Tomas-M** [comment]
Glad to hear, thanks for testing! :)
