### ISSUE TITLE
Scroll bar missing on white background

### ISSUE THREAD

**Issue by Botspot** [Tomas-M/xlunch#120]
`xlunch --bc ffffffff`
## Expected behavior:
A scroll bar is visible. Even if I can't click-n-drag it, it's visible.
## Actual behavior:
A scroll bar is not visible. At all.

If I switch to a darker background, the scroll bar becomes visible again.

**Comment by PMunch** [comment]
Yes, one of the few things that are still hard-coded in xlunch is the colour of the scrollbar. This should definitely be an option.

**Comment by PMunch** [comment]
The scrollbar and scrollbar indicator colours are now configurable.
