### ISSUE TITLE
Can I have a transparent background, but not transparent icons?

### ISSUE THREAD

**Issue by Botspot** [Tomas-M/xlunch#121]
Let's say I wanted xlunch to have a mostly-transparent, dark background: `xlunch --bc 00000070`

If the xlunch window is positioned above a dark-colored window, the icons look like:  
![2020-11-25-173122_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/100291701-187c1a00-2f44-11eb-93ab-b5c06f1cf0f6.png)  
Notice that you can see the text behind the icons. That's not what I want. I want the icons to remain opaque.  

But if the xlunch window is positioned above a light-colored window, the icons look like this:  
![2020-11-25-173218_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/100291738-334e8e80-2f44-11eb-9809-8c6f7b5d2c93.png)  
The icons are totally washed out and hard to see.

How difficult would it be to fix this?

**Comment by PMunch** [comment]
Hmm, I think this is actually a simple bug. Imlib is context-dependent, so maybe it sets the transparency and never resets it somewhere. I'll look into it.

**Comment by Botspot** [comment]
Wouldn't it be better to leave this issue open until the issue is fixed? (assuming you plan to fix it)

**Comment by PMunch** [comment]
I have fixed it, that's why I closed the issue. Wouldn't close it without fixing it.

**Comment by Botspot** [comment]
Oh I see.  
Will recompile.
