### ISSUE TITLE
Blur background?

### ISSUE THREAD

**Issue by Botspot** [Tomas-M/xlunch#123]
It would be really neat if xlunch had a blur background option.

So when it pops up, xlunch is a transparent window, but everything behind the xlunch window is blurred to some configurable extent.

Such an option could probably be achieved like this:

- Take a screenshot of the screen.
- Use some image manipulation library to blur it.
- Use this new image as xlunch's background.
- The image is deleted on exit, or was never written to disk in the first place.

Now, in windowed mode, if you dragged xlunch around, the background would not self-update and that would look funny, but that's probably a good thing. If it self-updated it would degrade performance too much to be usable on low-end PCs.

**Comment by PMunch** [comment]
This is really a bit out of scope for xlunch. But the thing you propose is possible to do without modifying xlunch. Just look at how something like the i3 blurlock is implemented.

Another option (which is better, but might be too demanding on an RPi) is to get your compositor to do this I know compton/picom has this ability at least.
