### ISSUE TITLE
Ability to add text/images where I want to, without them being clickable buttons?

### ISSUE THREAD

**Issue by Botspot** [Tomas-M/xlunch#124]
I'm planning on using xlunch to make an app store.

Currently, browsing through the list of apps is pretty good, however after you click an app, I'd like its description displayed on-screen, have a few buttons to configure it, and have the app's icon displayed somewhere on-screen.

Something like this:  
![2020-11-26-090738_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/100366775-e3fd7200-2fc6-11eb-976a-3f408b315864.png)

Is there a way to do this? I don't want the description clickable, or the image clickable.

**Comment by PMunch** [comment]
This is unfortunately not something xlunch was ever made to do. But you're in luck, because I'm currently working on a similar project called [notifishower](https://github.com/PMunch/notifishower)(name subject to change). Basically it started out as a configurable way to create notifications. But now it's so configurable that I'm adding modes like window, dock, fullscreen, and desktop to it. It would certainly be able to make that layout just fine.

**Comment by Botspot** [comment]
@PMunch Would your notifishower also be able to display a scrollable, searchable list of apps?

If possible, I'd like to stick to one dialog program for the whole app store, or at least one uniform look & feel for the whole thing.

**Comment by PMunch** [comment]
That is unfortunately not possible (as of now at least). But creating a cohesive look between xlunch and notifishower would be pretty simple.

**Comment by Botspot** [comment]
@PMunch okay thanks.

About the original post in this issue, I've determined that xlunch would completely satisfy all requirements of the app store, if I could have it display text. Could you add an additional parameter to the `--button` flag that allows text to be added under/next to the `--button`'s icon? That would seem like an easy setting to implement, and I think many xlunch users would use such a feature.

**Comment by PMunch** [comment]
Problem is that it really adds a whole lot of options for if the text should appear below/above/right of/left of/centered/aligned left-right etc. etc. etc. For most people it suffices to use the current buttons as they pre-generate images with the text on them. I think xlunch simply isn't the right tool for creating something like what you have in your image. Notifishower though, is.
