### ISSUE TITLE
Transparent --button entries should be subject to window background color

### ISSUE THREAD

**Issue by Botspot** [Tomas-M/xlunch#129]
# Setup:
xlunch with an opaque black background:
```
xlunch -bc 000000ff
```
I add a button to it:
```
xlunch -bc 000000ff \
--button "/path/to/proglogo.png;;0,0;"
```
# Expected behavior:
proglogo.png is displayed "above" the black background, and any transparency in the image is now black.
# Actual behavior:
proglogo.png punches a hole in the black background, and you can see right through the image to underlying elements.

Screenshot:  
![2020-11-27-122908_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/100476821-2fd61700-30ac-11eb-93aa-6f99a21a89af.png)

And here's proglogo.png, in case you wanted it for testing purposes:  
![proglogo](https://user-images.githubusercontent.com/54716352/100476659-c6560880-30ab-11eb-8668-c550a4ad7261.png)

Interestingly, when using a white background instead of a black one, this problem does not occur.

**Comment by PMunch** [comment]
Hmm, I think this might've been the thing that made icons translucent with a transparent background. What happens if you make the background ever so slightly translucent? We might need to add a logic switch in here somewhere.

**Comment by Botspot** [comment]
> Hmm, I think this might've been the thing that made icons translucent with a transparent background. What happens if you make the background ever so slightly translucent?

The problem still occurs on a semi-transparent black background.

Interestingly, when using a white background, this problem does not occur and the image is as opaque as the rest of the window.

**Comment by Tomas-M** [comment]
Should by fixed by PMunch's latest changes, releasing as version 4.7.2
@Botspot please test too

**Comment by Botspot** [comment]
> Should by fixed by PMunch's latest changes, releasing as version 4.7.2 @Botspot please test too

Looks great! I'll push necessary changes to Pi-Apps in a few minutes.
