### ISSUE TITLE
[Information] I add your program to AUR (ArchLinux User Repository)

### ISSUE THREAD

**Issue by DX37** [Tomas-M/xlunch#13]
Hello, Tomas! (I'm the biggest fan of Slax ever)

I have added your program as an package for building to the ArchLinux User Repository.

In the ArchLinux distribution we have a wonderful package manager pacman, which kinda recently added pre- and post-transaction hooks. They allow you to make any preliminary steps, and steps after install/update program.
I added to package hook, which generates icons.conf after every install/update/remove of any package with files in /usr/share/applications.

Please, have a look at files on AUR!
https://aur.archlinux.org/packages/xlunch-git/

**Comment by Tomas-M** [comment]
Hello, this is nice, thank you! :)
I do not fully understand how to view your pre-post transaction hooks, I would like just to make sure that you do not regenerate entire icons.conf file, only please add/remove the appropriate rows for the programs. Full regen would overwrite user's modifications and would would take very long time. Thanks for consideration! Maybe you already do this, in that case just ignore me :)

**Comment by DX37** [comment]
It's a little bit harder, but [here you go](https://aur.archlinux.org/cgit/aur.git/tree/xlunch-conf-regen.hook?h=xlunch-git) :)
And nope, I'm using your genconf to generate entire icons.conf. It's not takes too long, but maybe there's a way...
However, at this moment I don't know how to implement partial adding/removing config entries :/

**Comment by Tomas-M** [comment]
Hm, do you know, at the pre-install or post-install phase, what *.desktop files were installed with that installation? Because that way we know what lines of icons.conf to remove or add.

**Comment by DX37** [comment]
Hmm. Maybe I will do something with it tomorrow. Create another script or make it another way...

**Comment by DX37** [comment]
Well... I have added some new hooks and scripts. Many times tested and seems like it works more quickly with adding or removing entries now.
https://aur.archlinux.org/cgit/aur.git/tree/?h=xlunch-git

Of course, I did it in my specific way... :)

**Comment by DX37** [comment]
Oh... If you still thinking about doing new Slax based on ArchLinux, this news might disappoint you.
https://www.archlinux.org/news/phasing-out-i686-support/
