### ISSUE TITLE
.desktop file - use unique name for icon

### ISSUE THREAD

**Issue by arcolinuxz** [Tomas-M/xlunch#130]
Could you not use "launch" as icon name but something more unique to the application so icon developers can create a unique icon for it.

Thanks in advance. 

Sardi and surfn icon developer ;-)

![2021-03-25_07-13](https://user-images.githubusercontent.com/36679406/112427885-9e657180-8d3a-11eb-8dac-00cd32df6744.png)

**Comment by PMunch** [comment]
The icon is called `xlunch` isn't it? Ref.: https://github.com/Tomas-M/xlunch/blob/master/extra/genentries.desktop#L5

**Comment by arcolinuxz** [comment]
I am so ashamed. Bad eye-sight for sure.
The name is xlunch and I will make a nice icon for it.
My apologies.

**Comment by arcolinuxz** [comment]
![xlunch](https://user-images.githubusercontent.com/36679406/112626177-24afaf80-8e30-11eb-8e8b-992b82d2d7f6.png)
One icon for xlunch.
Again sorry to waste your time.

**Comment by PMunch** [comment]
No worries, didn't take me long to have a look in the desktop file. That icon looks great!
