### ISSUE TITLE
Center icons and increase margins 

### ISSUE THREAD

**Issue by rainer2208** [Tomas-M/xlunch#134]
Hi, I am trying out the XLunch launcher and find it very nice and responsive. 

What I couldn't find where any parameter to center the icons on the screen, like when using 2 columns and 2 rows. In this configuration, the icons automatically align to the sides, top and bottom, and I would like to position them in the middle/ middle.

Another thing I couldn't figure out was to increase the side, top and bottom margins. Is this possible?

**Comment by PMunch** [comment]
Have you read the documentation/`--help` message? You can use `--center` to center icons in their row when there are fewer icons than columns. It also seems like you might want to increase your border if you feel the icons are aligning to the sides. This can be done with `--border` and it takes pixels or a percentage of the screen width. You also have `--sideborder` to control the border on each side of the icons (`--border` applies to both if `--sideborder` is not given). There is also `--borderratio` and `--sideborderratio` to control if you don't want your applications to be placed in the middle but rather slightly to the left/right/top/bottom.
