### ISSUE TITLE
[false positiove] xlunch deleted all the svg icons in "/usr/share/icons/hicolor/scalable/apps/"

### ISSUE THREAD

**Issue by trappedinspacetime** [Tomas-M/xlunch#138]
First of all, I congratulate you on your project. I like it. The day before I built it. I think it converted `svg`icons to png in `/usr/share/icons/hicolor/scalable/apps/`. I noticed today that all the `svg` icons in `/usr/share/icons/hicolor/scalable/apps/` got deleted.

I had to reinstall all those applications to recover those icons.

**Comment by Tomas-M** [comment]
Hm, strange, what did you run?
There is no 'rm' command in any of the scripts as far as I know, so this is odd.

**Comment by trappedinspacetime** [comment]
I have been inspecting my command-line history. I remember a process asked elevated privileges via `pkexec` I don't remember exactly which application it was.

**Comment by Tomas-M** [comment]
So, why you think that your icons were deleted by xlunch?
I am sure that xlunch does not call pkexec at all.
It could be possible, for example, that xlunch generated a config file for you (with icons and commands to execute) and it made a mistake and generated some wrong command (which deleted your icons after you clicked certain icon in xlunch screen). If this was the case, it could help if you send here the configuration file generated by xlunch.

**Comment by trappedinspacetime** [comment]
@Tomas-M Thank you for responding. I checked out my `bash` history, there were a few commands I issued regarding `xlunch` from within  `xlunch` directory:

          ~/Desktop/01-2022 32038  2022-01-17-22:58:08 git clone https://github.com/Tomas-M/xlunch
          ~/Desktop/01-2022 32039  2022-01-17-22:58:27 cd xlunch/
          ~/Desktop/01-2022/xlunch 32040  2022-01-17-22:58:29 ls
          ~/Desktop/01-2022/xlunch 32041  2022-01-17-22:58:37 make 
          ~/Desktop/01-2022/xlunch 32043  2022-01-17-23:08:31 ls
          ~/Desktop/01-2022/xlunch 32044  2022-01-17-23:08:47 ./xlunch 
          ~/Desktop/01-2022/xlunch 32050  2022-01-17-23:34:03 ./xlunch --help 
          ~/Desktop/01-2022/xlunch 32051  2022-01-17-23:34:43 ./xlunch 
          ~/Desktop/01-2022/xlunch 32052  2022-01-17-23:35:17 ls /etc/xlunch/entries.dsv
          ~/Desktop/01-2022/xlunch 32053  2022-01-17-23:36:36 ./xlunch -i entries.dsv

[entries.dsv.txt](https://github.com/Tomas-M/xlunch/files/7916289/entries.dsv.txt)
[default.conf.txt](https://github.com/Tomas-M/xlunch/files/7916303/default.conf.txt)

**Comment by trappedinspacetime** [comment]
@Tomas-M I'm sorry for taking your time. I couldn't reproduce the issue. It might be my bad. I'll try to inspect my command-line history. I also built a few application from source and removed some of them via `make uninstall`, I'll rebuild and uninstall them again. 
I apologize for my `false positive` issue.

**Comment by trappedinspacetime** [comment]
I found the actual application which deletes `svg` files: https://github.com/chipmunk-sm/HexEditor/issues/9#issue-1111416510

**Comment by Tomas-M** [comment]
Thank you for the info! :)
