### ISSUE TITLE
Ctrl+P and Ctrl+N for selection

### ISSUE THREAD

**Issue by synaptiko** [Tomas-M/xlunch#14]
It would be great to add support for Ctrl+P and Ctrl+N for selecting programs to avoid usage of arrow keys. Similar to what's used in bash or vim for selection from a list of commands/options.

**Comment by Tomas-M** [comment]
I'm not sure what you mean. Ctrl+P and Ctrl+N cycles history in bash, is that what you want? That would require to maintain history of executed commands in some file. I am afraid that most users will not even know there is the possibility to use Ctrl+P or +N at all...

**Comment by synaptiko** [comment]
No, it wasn't meant for going through history it could work just as additional up and down arrows for selecting one of the filtered results (when typing a name). In vim you can use Ctrl+P/N also for going line by line up or down, that was what I was referring to.

Maybe it would be good to have configurable mappings for actions in xlunch but it's probably overkill…

Feel free to close this issue if you think it's all nonsense ;-) :-)

**Comment by Tomas-M** [comment]
Ah, now I can understand.
The problem for me is that in xlunch, keys pressed are identified by keycode. And the program checks for each keycode pressed, if it is Up or Down key etc, that's easy, but it cannot see Ctrl+P. It sees keycode for Ctrl key, and keycode for P key, as two separate keystrokes. So I do not know how to properly detect that Ctrl and P are pressed at the same time, I would have to implement hooks for key-release events or something, to detect Ctrl was pressed but not yet released. I prefer not to do that, sorry :)
