### ISSUE TITLE
Github release for 4.7.5

### ISSUE THREAD

**Issue by MIvanchev** [Tomas-M/xlunch#147]
Hey @Tomas-M, I saw the last release is for 4.7.1. You could maybe release 4.7.5 because it's easier for package maintainers to become aware of the version.

**Comment by PMunch** [comment]
Added new releases for all missing versions between 4.7.1 and 4.7.5. Thanks for reminding us!

**Comment by MIvanchev** [comment]
Thank you for this great software!
