### ISSUE TITLE
Add commandline option to position icons as well

### ISSUE THREAD

**Issue by l-e-e-o** [Tomas-M/xlunch#15]
So my monitor setup looks like this:

```
       +---+
+-----+|   |
|  1  || 2 |
+-----+|   |
       +---+
```
`xlunch` detects this as a 1920x(1920+1200) screen, which is fine, because I want to display xlunch on both monitors.  The problem is, that there are two sections of this "screen" which are not visible (above and below monitor 1). Although I can place the prompt lower on the "screen" so it lands in monitor 1 with `-t`, the icons remain in the invisible section above monitor 1.

I propose two changes:
* Allow positioning of the icons as well (e.g. with `-T`)
* Change options to also accept `x`-offsets (e.g. in the format `123x456`) to allow for more complex monitor setups which I also have not thought off

**Comment by Tomas-M** [comment]
`-b` won't help you?

**Comment by l-e-e-o** [comment]
It definitely would if I could specify each direction seperately (e.g. `-b <north>,<east>,<south>,<west>`)

**Comment by Tomas-M** [comment]
What about specifying `-a 0 -e 100 -y 1920 -z 900` ?

**Comment by l-e-e-o** [comment]
This only works on a single screen and I need to statically specify the background image. Using `-r` causes a segfault.

**Comment by Tomas-M** [comment]
OK please try newest release with -T parameter.
Is this what you wanted? :)

**Comment by Tomas-M** [comment]
Closing due to lack of feedback.
