### ISSUE TITLE
Doesn't show icons or run applications when used as a shortcut

### ISSUE THREAD

**Issue by Dale-CDL** [Tomas-M/xlunch#151]
I have xlunch set to a shortcut key on Xfce. It opens and only shows the Run: with no icons shown. When I type in an application name, xlunch exits without running the application.

When I open a terminal and type xlunch or xlunch -G (same as it is in the shortcut) it will show the icons and open the application I type in at the Run: prompt.

What do I need to do for it to work when executed from a keyboard shortcut?

Thanks,
Dale

**Comment by PMunch** [comment]
Try to run it from the shortcut with `-i entries_file.dsv`. By default xlunch tries to read from stdin, so if xfce for some reason writes anything there it won't read the entries file. Other than that it could be that the $HOME environment variable isn't set correctly. In either case `-i` should help.

**Comment by Dale-CDL** [comment]
Thanks, that fixed it. I now have it set as xlunch -tGi entries.dsv for my shortcut. I also created an xlunch folder under my .config. I then copied the entries.dsv from /etc/xlunch/.
