### ISSUE TITLE
Hard-coded binary and paths causes build problems on FreeBSD

### ISSUE THREAD

**Issue by willbprog127** [Tomas-M/xlunch#17]
Greetings!

Thanks for your cool app!

**Makefile**
`CC` is hard-coded to gcc, which causes problems on systems that use clang instead (ie: FreeBSD).  Can you instead test to see if `cc` is already a valid compiler command and just use it as-is?  If it's not already a valid compiler command, you could then test for gcc or clang and then assign one of those.

**extra/genconf**
The `APPS` and `ICONS` variables should be adjusted depending on the system.  As they are now, they work fine in Linux, but for FreeBSD (and possibly others) the paths are `/usr/local/share/applications` and `/usr/local/share/icons`.  Also it would be nice if xlunch got the .desktop files from ~/.local/share/applications.

Thank you so much! :smile:

**Comment by Tomas-M** [comment]
Hello, I do not know how to test for other compilers. Patches welcome :)

**Comment by willbprog127** [comment]
@Tomas-M Okay, I will work on it when I have some time :-)  Thank you Tomas!

**Comment by willbprog127** [comment]
@Tomas-M Sorry, haven't had time, and not using FreeBSD anymore.  Thanks! :+1:
