### ISSUE TITLE
Add an option to hide double entries

### ISSUE THREAD

**Issue by Smile4ever** [Tomas-M/xlunch#19]
Some applications have multiple desktop files. Okular has three different occurences in xlunch. Can this (optionally?) be reduced to one please? I think it's safe to assume the icon will be the same.

**Comment by Tomas-M** [comment]
Patches welcome :)

**Comment by PMunch** [comment]
I think this is a case of the .desktop files being in different folders. I think there is some order in which the files should be prioritized so that users can create a .desktop file in ~/.local/share/applications to override the .desktop file in /usr/share/applications

**Comment by Tomas-M** [comment]
Actually the user can simply edit the generated conf file in order to delete icons he doesn't like. The generator just blindly takes all programs and icons it finds. But the main intention is to let the user edit the conf file manually.

**Comment by PMunch** [comment]
Hmm, I guess that makes sense. But what happens if the user creates a custom file and then installs a program? Does the list update?

**Comment by Tomas-M** [comment]
Nope, it does not autoupdate.

**Comment by Tomas-M** [comment]
Ideal would be to update it each time user starts the software, but it is a time consuming operation, because there are so many icons in the system in so many folders and subfolders, so it cannot be done that way. Due to that I decided to use a simple configuration file.
