### ISSUE TITLE
Imlib2.h: no such file or directory

### ISSUE THREAD

**Issue by jgedri** [Tomas-M/xlunch#20]
When I ran 'make' from the xlunch folder, I got the following error:
`xlunch.c:10:20: fatal error: Imlib2.h: No such file or directory`

Where can I find the missing file/directory?

**Comment by Tomas-M** [comment]
You need Imlib2 to be installed.

**Comment by ghost** [comment]
pretty sure i have imlib2, still fails:

> /Apps/Linux/xlunch/ [master] **i libimlib2**
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libimlib2 is already the newest version (1.4.10-1).
libimlib2 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

> /Apps/Linux/xlunch/ [master] **make test**
```
gcc xlunch.c -o xlunch -lImlib2 -lX11 -O2 -s
xlunch.c:15:10: fatal error: Imlib2.h: No such file or directory
 #include <Imlib2.h>
          ^~~~~~~~~~
compilation terminated.
Makefile:43: recipe for target 'xlunch' failed
make: *** [xlunch] Error 1
```

Sysyem: Ubuntu 18.04

EDIT: turns out, only the `libimlib2-dev` has source files needed, so it must be added as a prerequisite for some distros

**Comment by Tomas-M** [comment]
Thank you for suggesting with `libimlib2-dev`
