### ISSUE TITLE
is it possible to add WM_CLASS or _NET_WM_PID ?

### ISSUE THREAD

**Issue by gcoda** [Tomas-M/xlunch#25]
This amazing project.
I wanted to leave it unmanaged by wm and ignored by compositor(compton).
It seems impossible without title or `WM_CLASS`/`_NET_WM_PID`

* it looks like wm or compositor is making it render extra frame by resizing or something.

**Comment by Tomas-M** [comment]
I completely missed your issue, sorry for late reply. If you specify -d and -f at the same time, it should override redirect, that means, it should be completely ignored by WM. Other solutions didn't work properly everywhere.
