### ISSUE TITLE
No images shown

### ISSUE THREAD

**Issue by PMunch** [Tomas-M/xlunch#28]
When I launch xlunch none of the icons are drawn. I checked the /etc/xlunch/icons.conf file and the icons there exists on disk and show up fine (they are PNG files). The log is peppered with Imlib error messages but I see there is an open Pull Request for that so I'm not sure if that necessarily means anything.

**Comment by Tomas-M** [comment]
I'm not sure what is the problem since I cannot replicate it. I've accepted the merge request which should probably mute the imlib errors, but won't help you show the images.
Can't replicate, so closing this issue. If you can show me how to replicate, please reopen.

**Comment by PMunch** [comment]
This was very likely related to svg images and possibly the pixmap folder. I don't know for sure until I can test it on the same machine as before tomorrow, but I think it should work now.

**Comment by PMunch** [comment]
Just got a chance to test this and I regret to inform you that it was not the case. I still get no images shown. I'll continue to research the issue.

**Comment by PMunch** [comment]
Found the error, and the fault was mine. Imlib on this system was split in multiple packages, one which contained the loaders. I was missing that package and therefore xlunch couldn't load any images. I've written a test in the `push_app` procedure that tries to load all images with the `imlib_load_image_with_error_return` call and a switch case on the enum values it has. This makes it easier for a user to debug why an image is not loaded.
