### ISSUE TITLE
Implement close button

### ISSUE THREAD

**Issue by Tomas-M** [Tomas-M/xlunch#3]
Currently it is possible to cancel the launcher only by pressing Esc key.
It should be possible to cancel it by clicking somewhere with mouse.
In ideal case, the user should be able to specify (using commandline argument) what icon file should be displayed and where. For example, if user is starting lunch from his taskbar by clicking some icon in bottom-left corner of screen, the same icon should be displayed at the same position to close lunch. This could provide very smooth usage.

**Comment by Tomas-M** [comment]
For now I have added possibility to close launcher by right mouse click.

**Comment by PMunch** [comment]
Maybe a background click to cancel? i.e. not clicking an icon? That would make it possible to use this on touch enabled machines.

**Comment by Tomas-M** [comment]
This seems as a good idea.
Perhaps by adding some parameter, which activates this feature.
Do you have a working patch to add?

**Comment by PMunch** [comment]
Sorry, just found the project earlier today and was looking through the issues. Haven't actually had time to look at how to implement it.
