### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by PMunch** [Tomas-M/xlunch#43]
Xlunch has a lot of options and it would be nice if we could implement a configuration file format that could be passed instead of switches for those who prefer that.

**Comment by PMunch** [comment]
Implemented in https://github.com/Tomas-M/xlunch/commit/3fdf27a4ce9ed3c3e571bacb11854593ec48355e. Any thoughts?

**Comment by Tomas-M** [comment]
Good work :)

Are comments allowed in the configuration file? Would be helpful, at least to support comments if line starts with hashtag or something. And ignore empty lines if there are any.

**Comment by PMunch** [comment]
Empty lines were already ignored, and as of https://github.com/Tomas-M/xlunch/commit/cf189ab5aed64685320066b55bc33872d8d45b0e all lines starting with # are ignored and all leading whitespace is ignored.

**Comment by PMunch** [comment]
Added a little note in the documentation about how you can actually use the `config` option in a configuration file to inherit styles from another file. This means you can split your system-wide display options into one file and have per-menu styles in separate files.

**Comment by PMunch** [comment]
After adding `#` as a comment you are also able to use shebangs to run the xlunch config files directly by adding `#!/usr/bin/xlunch --config` to the top of the file.

**Comment by Tomas-M** [comment]
This is very clever idea! :)

**Comment by Tomas-M** [comment]
I tried config using "shebangs"
I have a file with the following contents:

    #!/usr/bin/xlunch --config
    input: /tmp/entries.dsv
    columns: 2

When I run this file, xlunch starts, icons are indeed in 2 columns only, but entries are taken from /etc/xlunch/entries.dsv instead of /tmp/entries.dsv ... Am I doing anything wrong?

**Comment by Tomas-M** [comment]
Ugh sorry I had a typo in my script. Works fine. Ignore this. Sorry. Thanks. :-)

**Comment by Tomas-M** [comment]
One remark though. If I specify iconpadding: 41 in the config file, and I put trailing newline, then everything is fine. But if I remove the trailing newline, so the file ends with the "1" character, then padding is not set. So perhaps your parser requires a newline at the end, it could perhaps check for newline OR file end.

**Comment by PMunch** [comment]
Ah yeah, it would be possible to do that. I'll look into it.

**Comment by Tomas-M** [comment]
I'm reopening this issue since it seems like there is still the problem that if the last line of config file does not end with \n, the line is not parsed

**Comment by PMunch** [comment]
Hmm, strange. When I run it on my machine it works just fine without a trailing newline. Any particular option you are having trouble with?

**Comment by Tomas-M** [comment]
I have xlunch directory in /tmp
I create /tmp/xlunch/x script, which looks like this:

    #!/tmp/xlunch/xlunch --config
    iconsize: 128

If there is trailing newline at the end of the file, it works (icons as 128px). But if there is nothing at the end of the file, so the last character is the '8' character, icon size is not set. Hope this helps.

**Comment by PMunch** [comment]
Ah, turns out that my Vim was automatically adding a newline to the file when it saved it had to use my hex editor to be able to remove the trailing newline. Should be fixed now.

**Comment by Tomas-M** [comment]
:) Thank you, closing

**Comment by Tomas-M** [comment]
Ah, found another issue I think.
My xlunch config is like this:

    #!/tmp/xlunch/xlunch --config
    iconsize: 128
    selectonly

Now if there is no newline at the end of file, it even refuses to start (and prints help usage).

**Comment by PMunch** [comment]
Fixed again in https://github.com/Tomas-M/xlunch/commit/e219cf85aebbe8105bd234acbe754cb75f44178c, hopefully completely this time :P

**Comment by Tomas-M** [comment]
I am not sure what happened, but now I cannot use the shebang at all.
The below mentioned config does not work at all, regardless of newline at the end.

    #!/tmp/xlunch/xlunch --config
    iconsize: 128
    selectonly

Got unknown option in config file on line 2

By the way, when I noticed this problem, I realized xlunch prints long --help after the error message, so I submitted a patch now to print only short usage in case of error d8f957c41c78115e66723f1914afc7b689a26660. Just mentioning it here, since it touches the code probably involved by this bug, but my new patch does not cause the bug, just to let you know.

**Comment by PMunch** [comment]
Hmm, that is very strange. I just pulled master, did a clean make, copied your above config file into a file (only changed the xlunch path) and everything worked as expected..

Good idea with the exits by the way, it was a bit confusing that the error was always off-page.

**Comment by Tomas-M** [comment]
I don't understand, really. I did the same thing, clean git pull, clean make, copied config, and see screenshot.

![image](https://user-images.githubusercontent.com/2259370/33516129-9c862d0e-d76d-11e7-8b2c-f7f906de024d.png)

**Comment by Tomas-M** [comment]
I'm cloning using

    git clone https://github.com/Tomas-M/xlunch

**Comment by Tomas-M** [comment]
I'm trying on 32bit arch, may this be a problem?

**Comment by PMunch** [comment]
Very strange indeed, this is what I do:

```
[peter ~/Projects/xlunch (master) ] $ cat ./a
#!/home/peter/Projects/xlunch/xlunch --config
iconsize: 128
selectonly
[peter ~/Projects/xlunch (master) ] $ ./a
Error opening config file from .
Reverting back to system conf.
libpng warning: iCCP: known incorrect sRGB profile
 32 [peter ~/Projects/xlunch (master) ] $ hexdump a
0000000 2123 682f 6d6f 2f65 6570 6574 2f72 7250
0000010 6a6f 6365 7374 782f 756c 636e 2f68 6c78
0000020 6e75 6863 2d20 632d 6e6f 6966 0a67 6369
0000030 6e6f 6973 657a 203a 3231 0a38 6573 656c
0000040 7463 6e6f 796c 000a                    
0000047
[peter ~/Projects/xlunch (master) ] $ git status
On branch master
Your branch is up to date with 'origin/master'
```

Don't think the architecture should matter, but if that's the only thing that has changed then maybe.. I'm on 64bit Manjaro by the way.

**Comment by Tomas-M** [comment]
I am testing on Slax, which is 32bit and 64bit based on Debian, with the very same packages.
On Slax 64bit, xlunch works OK.
On Slax 32bit, xlunch does not work properly in this regard, config file with shebang does not work

On Slax 64bit, sizeof(long_options) is 1824, while on 32bit the sizeof(long_options) is 912. Is this correct?

I don't know what this sizeof() is for, but I would say it makes the problem.

**Comment by PMunch** [comment]
Aha, yes that would be the error. sizeof is used to determine the size of things in bytes. On 64bit architecture the pointers are 64bit meaning that the structure is longer. As you can see I divided them by 32, which on 64bit systems is the size of each option struct in longopts. This was done to get the number of options. I've changed them in my latest commit to use `sizeof(struct option)` instead which should make it work on 32bit architectures.

**Comment by Tomas-M** [comment]
Cool, works now, thanks! :)
