### ISSUE TITLE
PKGBUILD

### ISSUE THREAD

**Issue by flaketill** [Tomas-M/xlunch#45]
On PKGBUILD missing 2 files 

line 39 and 40

install -Dm755 extra/genconf "$pkgdir"/usr/bin/xlunch-genconf
install -Dm755 extra/sample_config.cfg "$pkgdir"/etc/xlunch/icons.conf

On the package not exist extra/genconf and extra/sample_config.cfg

**Comment by PMunch** [comment]
Hmm, yes the original PKGBUILD is not maintained by us (didn't even know there was one). I'll look into getting ownership over the package so I can update it with something that actually works..

**Comment by PMunch** [comment]
The PKGBUILD should now be up-to-date and working fine. I'm not on my Arch based system so I can't try it out right now, but I'll test it when I get home and close this issue.

**Comment by flaketill** [comment]
Thanks!

**Comment by DX37** [comment]
It's not built. Can't find one picture.
I say it as previous maintainer - I dropped package because of new generation script, which I used as a bse for `xlunch-conf-*` hooks and `xlunch-create-entry` (which wasn't empty, you accidentally deleted it).

And, OMG, your script is easier to examine than I expect. Maybe I can take back owner ship on package to fully update it? 😄
I will try to add you as contributor: to this package in AUR, or at least to PKGBUILD.

**Comment by PMunch** [comment]
I emptied it in the previous commit, AUR just wouldn't let me push with a file missing. I updated the script to have switches for the same thing that your xlunch-create-entry script did, and all the hooks are set up to use those switches when calling genentries. There is however an issue currently discussed on Reddit which seems to make genentries fail and not generate any entries. When that is resolved the current PKGBUILD should work fine.

**Comment by DX37** [comment]
Your script IS working. PKGBUILD just can't find one image. I assume that if I correct this mistake, package will be built correctly.

**Comment by PMunch** [comment]
No, I figured out what was actually wrong. It is pulling th wrong version of the repo when it's trying to install. I'm working on fixing it now.

**Comment by PMunch** [comment]
Okay, the PKGBUILD should work now. Again I'm not on my Arch machine so I can't test it right now, but I'm fairly certain that it should work.

**Comment by DX37** [comment]
There is several things, which is disappointing:
1. Unfortunately, there is no .gtkrc-2.0 in home directory, if user uses GNOME-based DE's on Arch.
2. Converting `*.svg` takes a lot of time and sometimes a lot of RAM.

**Comment by PMunch** [comment]
Yeah, the latest version of the script tries to take more DE/WM theme settings into consideration, but I'm sure I've missed some. Suggestions for more additions or better yet PRs are always welcome.

There isn't really a way to get around the SVG issue. I could of course create a switch to ignore SVG images and leave the entries without an image, but I'm not sure if people would use that. Plus, it's only a once per install thing and not something you have to do all the time. I tried looking for a C implementation SVG renderer to see if we could add another small dependency to render them natively. But short of depending on the rather large Cairo I couldn't find anything that would be better than this approach.
