### ISSUE TITLE
Fluxbox window position problem

### ISSUE THREAD

**Issue by Tomas-M** [Tomas-M/xlunch#51]
When running xlunch on FluxBox, there is a problem that the window is positioned like 20px from the top, leaving uncovered background there. If using --desktop then the problem is not there. So it has probably something to do with the window manager. It looks like if there was the space for window titlebar, while the titlebar is NOT there :)

I am not sure how to fix this. Maybe send some WM_something message?

**Comment by Tomas-M** [comment]
I found a way how to workaround the issue with fluxbox settings - it is possible to configure fluxbox to remove window decoration for a specified application, so it's possible to make it remove the deco for xlunch only, by using this in ~/.fluxbox/apps:

    [app] (name=xlunch)
    [Deco] {NONE}
    [end]

It would be great if we can make xlunch in a way that it informs fluxbox to do that on its own, without this setting. Until we find a way, this workaround can be used. @PMunch do you have any suggestion what WM_ message should we send to fluxbox to remove the window deco? Chromium somehow manages to work properly with fluxbox (removes window deco) so there must be a way.

**Comment by Tomas-M** [comment]
Maybe this helps
https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html

**Comment by Tomas-M** [comment]
Fluxbox has a 'tests' directory in its source, and this directory contains several c files including fullscreetest.cc ... if I compile this file, it is able to switch between windowed and fullscreen without any problem. And it uses the same _NET_WM_STATE_FULLSCREEN message, it seems nothing else. This is strange.

**Comment by PMunch** [comment]
I looked at the WM hints for Vivaldi (Chromium based) and a terminal. It appears that the hint we might want to set is the `_MOTIF_WM_HINTS` which can be set to hide decorations. However setting the window to full-screen is already hiding decorations, so I'm not sure that it will help. Is this when you run in the regular full screen mode, or when you're running it it windowed mode?

**Comment by Tomas-M** [comment]
Using no parameter for ./xlunch in fluxbox makes it appear as on the screenshot.
Using --window mode does not show the window decoration in fluxbox(!) and appears exactly like at the screenshot too.
Using --desktop is just fine in fluxbox (behaves as expected, real fullscreen)

So this may be a bug in fluxbox itself, or xlunch should explicitly set or hide the decorations by sending some message or hint, as you mentioned, to make it more universal.

![screen](https://user-images.githubusercontent.com/2259370/32219787-ae6c6e72-be2f-11e7-9420-96ac11eb60bd.png)

**Comment by Tomas-M** [comment]
_MOTIF_WM_HINTS ... this looks to me like something specific to Motif, which is some toolkit or something, not really sure if this is inside pure X11

**Comment by Tomas-M** [comment]
In fluxbox sources (in the test suite for fullscreen), they refer in a comment to Motif WM hints too. So perhaps this is the right direction. Perhaps fluxbox requires applications to explicitly show or hide the decoration.

**Comment by PMunch** [comment]
Yeah, Motif is an old toolkit. But since there wasn't any other way of defining this most window managers just started accepting Motif hints and therefore people outside Motif started using them. So It's kinda snowballed to become something else. Not really sure why fluxbox is not properly respecting the full-screen hint, that seems weird. So it might be a bug in fluxbox, or that it requires things to be done in a particular way.

**Comment by Tomas-M** [comment]
I agree it will be a bug in fluxbox. But we cannot fix fluxbox, so I would like to have a workaround in xlunch.
Do you know of a simple way how to use the motif hints to enable and disable window decorations?

**Comment by PMunch** [comment]
Probably something like [this](https://stackoverflow.com/questions/5134297/xlib-how-does-this-removing-window-decoration-work).

**Comment by Tomas-M** [comment]
The problem is gone after reinstalling fluxbox.
Very strange ... I'm closing this since I am unable to reproduce the problem any longer, sorry for wasting your time.
