### ISSUE TITLE
leastmargin specified using long option segfaults

### ISSUE THREAD

**Issue by Tomas-M** [Tomas-M/xlunch#52]
When I specify -l 20, it works fine.
But when I specify --leastmargin 20, xlunch segfaults and quits right before start.
I am not good at debugging, can you perhaps confirm that it works fine on your setup?
Commandline segfaulting:

     xlunch --leastmargin 20

**Comment by PMunch** [comment]
Ah, I had forgotten to mark the long option as taking an argument. Good thing you spotted it!

Fixed here: https://github.com/Tomas-M/xlunch/commit/18e152005b270a22a13b62df96ed08b376bc4336
