### ISSUE TITLE
Web site shows newest version

### ISSUE THREAD

**Issue by PMunch** [Tomas-M/xlunch#64]
The website always shows the newest version found in the master branch. This means that the download files might not have all the features the website mentions. If possible the website should point at the last tagged version.

**Comment by Tomas-M** [comment]
I have no idea how to do that :(

**Comment by PMunch** [comment]
Looked into it a bit and it seems to not be possible without some extra steps.. I've sent GitHub a support ticket for this but a solution that would work is obviously to have a `devel` branch with the current development and only pull from that into `master` whenever a new release is ready.

**Comment by Tomas-M** [comment]
I don't like having devel branch. I prefer master only. I will try to make a script which simplifies new release modifications and pushes a new tag to github, so we could run something like `make release` from command line and it will do all the work for us to update everything. Then we can make new release with each new feature easily.

**Comment by Tomas-M** [comment]
I am definitely not the best coder for this, so I tried. I've added `make release` target. It parses current version infos, prompts for new versions (you can confirm empty Enter to keep previous value) and then it patches some files and calls git push twice (I didn't figure out how to push master branch and --tags at the same time).

So every time you make some interesting changes, you may run `make release` and it will do the work for you. Feel free to rewrite it if you have the neeed :-)

**Comment by PMunch** [comment]
Just heard back from the GitHub support ticket:

> Hi Peter,
>
>Thanks for the feedback on this!
>
>This isn't currently possible to do I'm afraid as GitHub Pages will currently only serve the exact content that's in your master branch. I can see the benefits of such a workflow, so I've passed on this feedback to our team as a feature request.
>
>In the mean time, I think the workflow you suggested may be the best alternative for now–keeping your latest stable version in the master branch, and creating a develop branch for your unreleased next version.
>
>Thanks again for the feedback,
Thomas

**Comment by Tomas-M** [comment]
Closing, if you find out the current solution with `make release` is insufficient, feel free to reopen :)
