### ISSUE TITLE
With border auto, height does not consider text

### ISSUE THREAD

**Issue by Tomas-M** [Tomas-M/xlunch#65]
When calculating borders in the auto mode, width is OK, but height is not considering the height of text, so if I put 3 rows of small icons, those rows are overlapping, as can be seen here:

![1](https://user-images.githubusercontent.com/2259370/32823731-8267a160-c9de-11e7-84f6-922ae9710cd9.png)

**Comment by PMunch** [comment]
Turns out it was just an arithmetic error in the consideration of prompt height + spacing. I've fixed it locally and will push it along with some other fixes soon.

**Comment by PMunch** [comment]
Fixed in https://github.com/Tomas-M/xlunch/commit/4defb28b4ec3460205a8835918b3d8036c69ce7e

**Comment by Tomas-M** [comment]
Awesome, thank you :)
