### ISSUE TITLE
Accepting negative coordinates for x/y pos

### ISSUE THREAD

**Issue by Tomas-M** [Tomas-M/xlunch#68]
Since xlunch can be used as a software for non-fullscreen menus, user may wish to put it to the bottom of the screen without knowing how big his screen is. Similarly as like buttons work accepting negative coordinates to put icons relative to bottom or right, we could support -x and -y positions to be negative too, in order to make the xlunch window positioned relative to bottom or right side of the screen.

That way, since I have a 20px high taskbar, I could use -x 0 -y -20 and the window (like a menu) would be placed just above the taskbar (window height would need to be subtracted similarly as icon height is subtracted when button is positioned on a negative position).

**Comment by PMunch** [comment]
Hmm, problem with this is that we need to figure out screen sizes, positions, etc. to get the proper position the user expects. Of course just using the full size of the X display would be better than nothing, but it's not perfect.

**Comment by Tomas-M** [comment]
I understand. Initially I added the possibility to set the x/y/w/h coordinates by the user just for the cases where xlunch was not positioned correctly - eg on screens with multiple displays, to let the user force it manually. Now I thought we could add similar functionality as for buttons using the negative numbers, but it is not such important. I can surely position the "xlunch menu" on my screen by using fluxbox settings, so I'm closing this.
