### ISSUE TITLE
Authors

### ISSUE THREAD

**Issue by Tomas-M** [Tomas-M/xlunch#70]
@PMunch If you don't mind I would suggest that you put your name to the AUTHORS file, as well as the website, because you are now much more author of xlunch than me :)

**Comment by PMunch** [comment]
Haha, good point. Something like this: https://github.com/Tomas-M/xlunch/commit/b9c395be491b38490413119c8d4cbaad046d6dca ?

**Comment by Tomas-M** [comment]
Cool :]
