### ISSUE TITLE
Enter key does nothing

### ISSUE THREAD

**Issue by Tomas-M** [Tomas-M/xlunch#72]
If I run xlunch with no parameters, so it shows icons from /etc/xlunch/entries.dsv and sets everything to defaults, it does not execute anything if I select an icon with keyboard and press Enter. Works with mouse, but not with keyboard. I would expect it to execute the given command under the icon even if only keyboard was used to navigate to it.

Using --selectonly helps, but I do not want to use this option since I prefer to let user run arbitrary command from the Run commandline.

**Comment by PMunch** [comment]
I had removed a `hoverset = KEYBOARD` line by accident. Fixed now.
