### ISSUE TITLE
Feature request: comment support in the entries file

### ISSUE THREAD

**Issue by neuromancer** [Tomas-M/xlunch#77]
It could be nice to have support to add comments in the entries files. Maybe we just ignore lines starting with `#` or `//`.  For instance:

```
# emulators
ZSnes;extra/zsnes.png;/usr/bin/zsnes
Desmume;entra/desmume.png;/usr/bin/desmume
```

**Comment by Tomas-M** [comment]
I thought it is already implemented. Did you try that?

**Comment by neuromancer** [comment]
Yes. It fails. You can add comments in the `config` file but not in the `entries` file (using the `--input` parameter)

**Comment by Tomas-M** [comment]
@PMunch would you please look at it? Thank you

**Comment by PMunch** [comment]
Hmm, yeah I implemented it but only for configuration files. To be honest I just didn't think about adding it to the entries parsing. When I receive feedback on #78 I'll look into it as both require changes to the parser and it's easier to do them both at the same time :)

**Comment by neuromancer** [comment]
Thanks!

**Comment by PMunch** [comment]
Comments should be implemented in the latest version now (with `#` as the comment character). I also redid the parsing a bit so adding sections to the parser should be relatively easy. Still have to figure out how to do it as an implementation though..

**Comment by neuromancer** [comment]
Thanks!
