### ISSUE TITLE
desktop mode does not accept keyboard input

### ISSUE THREAD

**Issue by corfizz** [Tomas-M/xlunch#79]
I have the following line in my i3 config file:
`exec --no-startup-id xlunch -d -q -s 64`
However xlunch does not accept keyboard input in this case.

**Comment by PMunch** [comment]
Yes, this is because xlunch is outside the windows managers control in this mode(`-d, --desktop`) and won't be getting any input events. This is documented on the [website](http://xlunch.org/). To remove the prompt (as it doesn't do anything in this mode) use `-n, --noprompt`.

**Comment by corfizz** [comment]
Ok, thanks, I must have missed/misunderstood it.
