### ISSUE TITLE
Side border ratio

### ISSUE THREAD

**Issue by aledthom** [Tomas-M/xlunch#80]
How do you specificy this ratio? It looks like I should be able to have a border each side with different sizes, however when I set it to anything less than 50 I get no border on the left and double on the right, and anything over 50 gives double border on the left and no border on the right. Setting it to 50 gives equal border each side.
I'm trying to shift the columns slightly left as I have a fixed menu down the right hand side using --button 's , seems like it should work with "sideborderratio:40" but that just does the same as "sideborderratio:0"?

**Comment by PMunch** [comment]
Ah, a simple arithmetic bug caused by using integers and not floats. Unfortunately I don't have git access on my computer right now, but I'll push the fix as soon as possible

**Comment by PMunch** [comment]
Ah, a simple arithmetic bug caused by using integers and not floats. Unfortunately I don't have git access on my computer right now, but I'll push the fix as soon as possible

**Comment by PMunch** [comment]
This should be fixed by https://github.com/Tomas-M/xlunch/commit/1a7f58f0a3daf1b65f3b13a0c9c2cbfdec0e23ee, can you confirm?

**Comment by aledthom** [comment]
Thanks, I'll have a look later, I'm currently reinstalling my laptop so it'll be busy for a while...

**Comment by PMunch** [comment]
Did you get a chance to test it?

**Comment by aledthom** [comment]
Just tried it now, working as expected now, great work!
