### ISSUE TITLE
Remove commandline and icontext

### ISSUE THREAD

**Issue by Vitalic66** [Tomas-M/xlunch#82]
Hallo,

i'd like to use xlunch as desktop on my RPi3. I use it as carputer. I just need to launch 3 to 4 apps (Openauto,  Kodi, maybe Firefox).

So i would like to have a launcher with 2 x 2 icons.

An option for the config would be great to set these 2 options.

**Comment by Tomas-M** [comment]
There is --columns 2 --rows 2

**Comment by PMunch** [comment]
Not entirely sure what you mean. If you set `--rows 2` and `--columns 2` you will get a 2x2 grid. If you run it with `--desktop` and `--dontquit` it will run as your desktop (and be under any open windows) and don't quit when you run something. If you want to remove the prompt text you can do `--noprompt`. Getting rid of icon text is a bit trickier. First you need to not specify any text for any of your icons, and then you set the font to any valid font with fontsize 0 and set `--textpadding 0`. Maybe that should be made a switch as well..

**Comment by Tomas-M** [comment]
closing for no feedback
