### ISSUE TITLE
Installation on Fedora

### ISSUE THREAD

**Issue by orschiro** [Tomas-M/xlunch#95]
Dear @Tomas-M et al,

This looks very promising and I look forward to testing it. :) 

Does anyone have an rpm package for easy installation on Fedora systems?

Yours

**Comment by PMunch** [comment]
Don't think there's a Fedora package, at least I don't know of one. But the Makefile is pretty easy to use for installation, just run "make install".

**Comment by orschiro** [comment]
Thanks @PMunch, 

Meanwhile and until we get a proper package, let's update the instructions: https://github.com/Tomas-M/xlunch/pull/96

**Comment by tim77** [comment]
[Available in COPR repos](https://copr.fedorainfracloud.org/coprs/atim/xlunch/) and working out of box. Will try to push in official repos.
