### ISSUE TITLE
paddingswap

### ISSUE THREAD

**Issue by Tomas-M** [Tomas-M/xlunch#98]
I would like to make xlunch more usable by default (when started without parameters and without config file). To do that, there are (imho) three things needed:
1) make wider icons padding (=40)
2) reverse behavior of paddingswap
3) enable scrolling by default

I always want the text to be displayed as like when paddingswap is used. Thus I always need to specify paddingswap. I cannot imagine situation where user would like to have the default behavior (the current behavior without paddinswap). So, I would like to make it the default.

I propose the following change to xlunch:
1) Reverse the behavior of paddingswap. By default, put text near the icons, and only put text far from the icons if --paddingswap parameter is specified. 
2) Rename --scroll to --noscroll and make the scroll option enabled by default
3) Make default icon padding 40

This change is not backward compatible so it will require major version increase.
What do you think? Can you live with this change? I strongly wish this to happen.

**Comment by PMunch** [comment]
I have no objections to this, but I think that if we should do it we should go over all the defaults and check that t hey make sense. A lot of things were set as default to be backwards compatible, and if we are first breaking something we might as well make sure we don't have to do it again soon.

**Comment by Tomas-M** [comment]
Good idea. I went through all the other parameters and I am happy with their default values at the moment, so I have no other requests for change. Do you suggest any?

**Comment by PMunch** [comment]
Looked through my configurations and couldn't really find anything that I think should be default. So if you haven't found anything then just good ahead :)

**Comment by Tomas-M** [comment]
OK, I made the changes and updated the version. Closing ticket
